/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fvtimetracker.gui;

import fvtimetracker.data.Datastore;
import java.awt.LayoutManager;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.*;

/**
 *
 * @author lachlan
 */
public class EditingDisplay extends javax.swing.JPanel {

	private Datastore datastore;
	private boolean layoutAlreadySet;
	private DefaultListModel<String> taskListModel;
	private DateFormat dateFormat;

	/**
	 * Creates new form EditingDisplay
	 */
	public EditingDisplay() {
		this(null);
	}

	public EditingDisplay(Datastore datastore) {
		this.datastore = datastore;

		taskListModel = new DefaultListModel<>();
		dateFormat = DateFormat.getDateTimeInstance();

		initComponents();
	}

	public void reset() {
		updateState();
	}

	@Override
	public void setLayout(LayoutManager mgr) {
		if (layoutAlreadySet) {
			return;
		}
		layoutAlreadySet = mgr instanceof GroupLayout;
		super.setLayout(mgr);
	}

	public void updateState() {
		List<String> tasks = datastore.getTasks();

		taskListModel.clear();
		for (String task : tasks) {
			taskListModel.addElement(task);
		}


	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        taskLst = new javax.swing.JList();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        taskDetailsLbl = new javax.swing.JLabel();

        taskLst.setModel(taskListModel);
        taskLst.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        taskLst.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                taskLstValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(taskLst);

        editBtn.setText("Edit...");
        editBtn.setEnabled(false);
        editBtn.setPreferredSize(new java.awt.Dimension(205, 30));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setText("Delete All");
        deleteBtn.setEnabled(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE))
            .addComponent(taskDetailsLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskDetailsLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn)))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void taskLstValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_taskLstValueChanged
		editBtn.setEnabled(!taskLst.isSelectionEmpty());
		deleteBtn.setEnabled(!taskLst.isSelectionEmpty());

		if (!taskLst.isSelectionEmpty()) {
			String task = (String) taskLst.getSelectedValue();

			long[] data = datastore.getTaskInformation(task);

			taskDetailsLbl.setText("Task '" + task + "', total hours: <"
					+ Math.ceil(data[0] / 60f) + ", last used: "
					+ dateFormat.format(new Date(data[1])));
		}
	}//GEN-LAST:event_taskLstValueChanged

	private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
		String original = (String) taskLst.getSelectedValue();
		String newTask = JOptionPane.showInputDialog(this,
				"Enter the new name of the task", original);

		if (newTask == null) {
			return;
		}

		datastore.renameTask(original, newTask);
		updateState();
	}//GEN-LAST:event_editBtnActionPerformed

	private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
		datastore.deleteTask((String) taskLst.getSelectedValue());
		updateState();
	}//GEN-LAST:event_deleteBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel taskDetailsLbl;
    private javax.swing.JList taskLst;
    // End of variables declaration//GEN-END:variables
}
