/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fvtimetracker.gui;

import fvtimetracker.data.Datastore;
import java.awt.LayoutManager;
import java.text.NumberFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lachlan
 */
public class HoursPerTaskDisplay extends javax.swing.JPanel {

	private Datastore datastore;
	private NumberFormat hourFormat;
	private boolean layoutAlreadySet;

	public HoursPerTaskDisplay() {
		this(null);
	}

	/**
	 * Creates new form HoursPerTaskDisplay
	 */
	public HoursPerTaskDisplay(Datastore datastore) {
		this.datastore = datastore;
		hourFormat = NumberFormat.getNumberInstance();
		hourFormat.setMinimumFractionDigits(2);
		hourFormat.setMaximumFractionDigits(2);

		initComponents();

		limitStartSpnr.setEditor(new JSpinner.DateEditor(limitStartSpnr,
				"dd/MM/yyyy"));
		limitEndSpnr.setEditor(new JSpinner.DateEditor(limitEndSpnr,
				"dd/MM/yyyy"));
	}

	public void reset() {
		Calendar now = Calendar.getInstance();
		now.set(Calendar.MILLISECOND, 0);
		now.set(Calendar.SECOND, 0);
		now.set(Calendar.MINUTE, 0);
		now.set(Calendar.HOUR, 0);

		Calendar startOfMonth = (Calendar) now.clone();
		startOfMonth.set(Calendar.DAY_OF_MONTH, 1);

		if (startOfMonth.equals(now)) {
			startOfMonth.add(Calendar.MONTH, -1);
		}

		((SpinnerDateModel) limitStartSpnr.getModel()).setValue(startOfMonth.
				getTime());
		((SpinnerDateModel) limitEndSpnr.getModel()).setValue(now.getTime());
	}

	@Override
	public void setLayout(LayoutManager mgr) {
		if (layoutAlreadySet) {
			return;
		}
		layoutAlreadySet = mgr instanceof GroupLayout;
		super.setLayout(mgr);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        hoursPerTaskTbl = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        limitStartSpnr = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        limitEndSpnr = new javax.swing.JSpinner();

        hoursPerTaskTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Task", "Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        hoursPerTaskTbl.setEnabled(false);
        jScrollPane1.setViewportView(hoursPerTaskTbl);

        jLabel2.setText("Limit between");

        limitStartSpnr.setModel(new javax.swing.SpinnerDateModel());
        limitStartSpnr.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                limitStartSpnrStateChanged(evt);
            }
        });

        jLabel1.setText("and");

        limitEndSpnr.setModel(new javax.swing.SpinnerDateModel());
        limitEndSpnr.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                limitEndSpnrStateChanged(evt);
                limitEndSpnrlimitSpnrsLimitChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(limitStartSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, 103, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(limitEndSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, 103, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(limitStartSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(limitEndSpnr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
    }// </editor-fold>//GEN-END:initComponents

	private void limitStartSpnrStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_limitStartSpnrStateChanged
		updateState();
	}//GEN-LAST:event_limitStartSpnrStateChanged

	private void limitEndSpnrStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_limitEndSpnrStateChanged
		updateState();
	}//GEN-LAST:event_limitEndSpnrStateChanged

	private void limitEndSpnrlimitSpnrsLimitChange(//GEN-FIRST:event_limitEndSpnrlimitSpnrsLimitChange
			javax.swing.event.ChangeEvent evt) {//GEN-HEADEREND:event_limitEndSpnrlimitSpnrsLimitChange
	}//GEN-LAST:event_limitEndSpnrlimitSpnrsLimitChange

	public void updateState() {
		DefaultTableModel model = ((DefaultTableModel) hoursPerTaskTbl.getModel());
		model.setRowCount(0);

		long start, end;
		start = ((SpinnerDateModel) limitStartSpnr.getModel()).getDate().getTime();
		end = ((SpinnerDateModel) limitEndSpnr.getModel()).getDate().getTime();

		List<String[]> tasks = datastore.getTasksTimes(
				start, end);

		if (tasks != null) {
			for (String[] taskTime : tasks) {
				int mins = Integer.parseInt(taskTime[1]);
				float hours = mins / 60f;
				taskTime[1] = hourFormat.format(hours) + "h";
				model.addRow(taskTime);
			}
		}
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable hoursPerTaskTbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner limitEndSpnr;
    private javax.swing.JSpinner limitStartSpnr;
    // End of variables declaration//GEN-END:variables
}
