/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package fvtimetracker.gui;

import fvtimetracker.Main;
import fvtimetracker.logic.ApplicationManager;
import javax.swing.JFrame;

/**
 *
 * @author lachlan
 */
public class ReturnToComputerPopup extends JFrame {

	private ApplicationManager applicationManager;

	public ReturnToComputerPopup(ApplicationManager applicationManager) {
		this.applicationManager = applicationManager;

		initComponents();
		pack();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        returnBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("FV Time Tracker - Away From Computer");
        setResizable(false);

        returnBtn.setText("Return to Computer");
        returnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(returnBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	public void showPopup() {
		if (isVisible()) {
			return;
		}

		setAlwaysOnTop(applicationManager.getAlwaysOnTop());

		setVisible(true);
		pack();
	}

	@Override
	public void setVisible(boolean b) {
		if (b == true) {
			setLocation(Main.PREF_ROOT.getInt("rtcpopup-x", 0), Main.PREF_ROOT.
					getInt("rtcpopup-y", 0));
		} else {
			Main.PREF_ROOT.putInt("rtcpopup-x", getX());
			Main.PREF_ROOT.putInt("rtcpopup-y", getY());
		}

		super.setVisible(b);
	}

	private void returnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnBtnActionPerformed
		applicationManager.startTiming();
		setVisible(false);
	}//GEN-LAST:event_returnBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton returnBtn;
    // End of variables declaration//GEN-END:variables
}
