/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package graphalgorithms.gui;

import graphalgorithms.algorithms.DijkstraAlgorithm;
import graphalgorithms.generator.Generator;
import graphalgorithms.graph.Graph;
import graphalgorithms.graph.Node;
import graphalgorithms.table.BellmanFordTable;
import graphalgorithms.table.DijkstraTable;
import java.security.SecureRandom;
import java.util.*;

/**
 *
 * @author lachlan
 */
public class MainFrame extends javax.swing.JFrame {

	private final Generator generator;

	/**
	 * Creates new form MainFrame
	 */
	public MainFrame() {
		generator = new Generator();

		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        graphView1 = new graphalgorithms.gui.GraphView();
        jPanel2 = new javax.swing.JPanel();
        dijkstraAnswer = new graphalgorithms.gui.AlgorithmTableView();
        jPanel3 = new javax.swing.JPanel();
        bellmanAnswer = new graphalgorithms.gui.AlgorithmTableView();
        messageTxt = new javax.swing.JLabel();
        newProblemBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        randomiseBtn = new javax.swing.JButton();
        solveForTxt = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Graph Algorithms");

        javax.swing.GroupLayout graphView1Layout = new javax.swing.GroupLayout(graphView1);
        graphView1.setLayout(graphView1Layout);
        graphView1Layout.setHorizontalGroup(
            graphView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 528, Short.MAX_VALUE)
        );
        graphView1Layout.setVerticalGroup(
            graphView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 470, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graphView1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graphView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Network Problem", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dijkstraAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dijkstraAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Dijkstra Answer", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bellmanAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bellmanAnswer, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Bellman-Ford Answer", jPanel3);

        messageTxt.setText("Welcome to Graph Algorithms test.");

        newProblemBtn.setText("New Problem");
        newProblemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProblemBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("<html>Please Note: there is an issue with the New Problem generator - sometimes it fails to properly work and may leave a blank map. If this happens keep trying or exit the program.</html>");

        randomiseBtn.setText("Randomly Rearrange");
        randomiseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                randomiseBtnActionPerformed(evt);
            }
        });

        solveForTxt.setFont(solveForTxt.getFont().deriveFont(solveForTxt.getFont().getSize()+8f));
        solveForTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        solveForTxt.setText("Solve For ?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(jTabbedPane1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(newProblemBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(randomiseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(solveForTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(messageTxt)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(messageTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(solveForTxt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newProblemBtn)
                    .addComponent(randomiseBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void newProblemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProblemBtnActionPerformed
		newProblem();
	}//GEN-LAST:event_newProblemBtnActionPerformed

	private void randomiseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_randomiseBtnActionPerformed
		graphView1.randomise();
	}//GEN-LAST:event_randomiseBtnActionPerformed

	public void newProblem() {
		long start = System.currentTimeMillis();
		while (!generateProblem() && System.currentTimeMillis() - start < 1000);

		solveProblem();
	}

	private boolean generateProblem() {
		Graph graph = generator.generate();

		if (graph == null) {
			return false;
		}

		graphView1.setGraph(graph);
		graphView1.repaint();
		return true;
	}

	private void solveProblem() {
		Graph g = graphView1.getGraph();
		Node base = generator.chooseBase(g);


		// Dijkstra's
		DijkstraTable dijTable = new DijkstraTable(g, base);
		dijkstraAnswer.setTable(dijTable);


		// Bellman-Ford
		BellmanFordTable bfTable = new BellmanFordTable(g, base);
		bellmanAnswer.setTable(bfTable);


		solveForTxt.setText("Solve For " + base.toString());
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private graphalgorithms.gui.AlgorithmTableView bellmanAnswer;
    private graphalgorithms.gui.AlgorithmTableView dijkstraAnswer;
    private graphalgorithms.gui.GraphView graphView1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel messageTxt;
    private javax.swing.JButton newProblemBtn;
    private javax.swing.JButton randomiseBtn;
    private javax.swing.JLabel solveForTxt;
    // End of variables declaration//GEN-END:variables
}
