/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package niawtscan.gui;

import java.io.File;
import javax.swing.JPanel;

/**
 *
 * @author lachlan
 */
public class FileBrowser extends JPanel {

	private File file;
	private boolean chooseFolders;

	/**
	 * Creates new form FileBrowser
	 */
	public FileBrowser() {
		initComponents();

		chooseFolders = false;
		
		setBrowseText("Browse");
		setFile(new File("."));
	}

	public void setBrowseText(String text) {
		browseBtn.setText(text + "...");
	}

	public String getBrowseText() {
		return browseBtn.getText().substring(0, browseBtn.getText().
				length() - 3);
	}

	public void setFile(File file) {
		this.file = file.getAbsoluteFile();
		fileNameTxt.setText(file.getAbsolutePath());
	}

	public File getFile() {
		if (chooseFolders && !file.isDirectory()) {
			file = file.getParentFile();
		}
		
		return file;
	}

	public void setFilename(String filename) {
		setFile(new File(filename));
	}

	public String getFilename() {
		return getFile().getAbsolutePath();
	}

	public void setChooseFolders(boolean chooseFolders) {
		this.chooseFolders = chooseFolders;
	}

	public boolean getChooseFolders() {
		return chooseFolders;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileNameTxt = new javax.swing.JTextField();
        browseBtn = new javax.swing.JButton();

        browseBtn.setText("Browse...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(fileNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 339, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(browseBtn))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(fileNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(browseBtn))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton browseBtn;
    private javax.swing.JTextField fileNameTxt;
    // End of variables declaration//GEN-END:variables
}
